stages:
  prepare_dataset:
    cmd: python -m mllam_data_prep data/datastore.yaml
      --output data/datastore.zarr
    deps:
    - data/datastore.yaml
    outs:
    - data/datastore.zarr
  create_graph-slurm:
    cmd: python -m neural_lam.create_graph
      --config_path data/config.yaml --name 1level --levels 1
    params:
    - data/config.yaml:
      - datastore
    deps:
    - data/datastore.zarr
    outs:
    - data/graph/
  train-slurm:
    cmd:
    - python train_wrapper.py --config_path $PWD/data/config.yaml
    params:
    - data/training_params.yaml:
      - model
      - graph
      - epochs
      - batch_size
      - hidden_dim
      - num_workers
      - processor_layers
      - metrics_watch
      - logger
      - val_steps_to_log
    deps:
    - versions.yaml
    - data/graph/
    - data/config.yaml
    - data/training/dataset.zarr
    outs:
    - saved_models
    metrics:
    - training/metrics/metrics.yaml
  evaluate:
    cmd:
    - python train_wrapper.py --config_path
      $PWD/data/config.yaml --eval val --load $PWD/saved_models/*/last.ckpt
    params:
    - data/training_params.yaml:
      - model
      - graph
      - epochs
      - batch_size
      - hidden_dim
      - num_workers
      - processor_layers
      - metrics_watch
      - logger
      - val_steps_to_log
    deps:
    - versions.yaml
    - data/graph/
    - data/config.yaml
    - data/training/dataset.zarr
    - saved_models
    plots:
    - evaluation/plots
plots:
- plots:
