# dvc parameters listed under `vars` will not be tracked
#  which is used to list settings that do not affect the
#  training or evaluation of the model, e.g. which logger
#  has been used.
vars:
  - logger: mlflow
stages:
  mllam_version:
    cmd: ${venv_path}/bin/python -c "from neural_lam import __version__; print(__version__)" > version.mllam.txt
  prepare_dataset:
    cmd: sbatch -W machines/slurm.mllam-data-prep.sh data/datastore.yaml --output data/datastore.zarr
    deps:
    - data/datastore.yaml
    outs:
    - data/datastore.zarr
  create_graph:
    cmd: ${venv_path}/bin/python -m neural_lam.create_graph --config_path data/config.yaml ${graph-defaults}
    params:
    - data/config.yaml:
      - datastore
    deps:
    - data/datastore.zarr
    outs:
    - data/graph/
  train:
    cmd:
    - VENV_PATH=${venv_path} sbatch -W ${slurm-defaults} machines/slurm.train.sh --config_path ./data/config.yaml --logger ${logger} --logger_project ${logger_project} ${baseline-defaults}
    deps:
    - version.mllam.txt
    - data/graph/
    - data/config.yaml
    - data/datastore.yaml
    outs:
    - saved_models
  evaluate:
    cmd:
    - VENV_PATH=${venv_path} sbatch -W ${slurm-eval} machines/slurm.train.sh --config_path ./data/config.yaml --eval val --load
      ./saved_models/*/last.ckpt --logger mlflow --logger_project ${logger_project} ${baseline-eval}
    deps:
    - version.mllam.txt
    - data/graph/
    - data/config.yaml
    - data/datastore.yaml
    - saved_models
    outs:
    - mlruns
